### ISSUE TITLE
VST Crash

### ISSUE THREAD

**Issue by iesv** [obsproject/obs-vst#78] opened 2021-02-25 09:35 UTC
![obs-bug](https://user-images.githubusercontent.com/16969250/109132831-39e0e200-778f-11eb-901d-02cd5d61ccfd.gif)
[VST Crash.txt](https://github.com/obsproject/obs-studio/files/6041933/VST.Crash.txt)

## Platform

Operating system and version: win10 x64 1809 LTSC
OBS Studio version: 26.1.1

## Steps to Reproduce

1. add tal-reverb of vst filter for vlc
2. increase the wet and delay
3. close the window
4. change the vst plugin
5. crash

**Comment by walker-WSH** [comment] 2021-11-26 00:49
I can't reproduce it with reaxcomp-standalone.dll.
I guess you are using a different version.

Can you upload your reaxcomp-standalone.dll ?

![1637887691](https://user-images.githubusercontent.com/18413354/143511217-ace9c933-aace-4325-b09f-7ea2c976e1d8.png)

**Comment by walker-WSH** [comment] 2022-01-14 01:04
I find the steps to reproduce : Crash happen while applying chunk-data of TAL_reverb.dll to reaxcomp-standalone.dll.
Besides, callstack of https://github.com/obsproject/obs-vst/issues/77 is same with it, so I think the two issues are same.

This crash has been fixed in https://github.com/obsproject/obs-vst/pull/101
So issue can be closed now. @WizardCM

**Closed as completed** 2022-01-14 01:12 UTC
